### ISSUE TITLE
[Feature]: line break latest reply

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmyBB#68]
### Is your proposal related to a problem?

long entry names are displayed in multiple lines.
![image](https://user-images.githubusercontent.com/12276250/203546620-840f5283-86fa-493c-92ff-38eb18df4596.png)

### Describe the solution you'd like

shorten the post names via css

### Additional context

![image](https://user-images.githubusercontent.com/12276250/203546493-1cae3fcf-d385-47c3-9d39-235823d3ec84.png)

```css
a.lastsubject {
  font-weight: bold;
  text-decoration: none;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  width: 235px;
}
```
